<?php
/**
 * Pinterest platform.
 *
 * @package EvzenLeonenko\OpenGraphControl
 */

declare(strict_types=1);

namespace EvzenLeonenko\OpenGraphControl\Platforms;

use EvzenLeonenko\OpenGraphControl\Renderer\Tag;
use EvzenLeonenko\OpenGraphControl\Resolvers\Context;

/**
 * Pinterest reads og:* for basic cards and application/ld+json (schema.org
 * Article / Product / Recipe) for Rich Pins. The JSON-LD payload is
 * generated by Platforms\Pinterest::json_ld in Phase 16; for MVP this class
 * emits no extra meta tags.
 */
final class Pinterest extends AbstractPlatform {

	public function slug(): string {
		return 'pinterest';
	}

	/**
	 * @return Tag[]
	 */
	public function tags( Context $context ): array {
		return [];
	}
}
